name: IssueHandler
on:
  repository_dispatch:
    types: [create-issue]

jobs:
  create-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Open Issue
        run: |
          gh issue create \
            --title "${{ github.event.client_payload.title }}" \
            --body "${{ github.event.client_payload.body }}" \
            --label "automated-report"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
