name: IssueHandler
on:
  repository_dispatch:
    types: [create-issue]

jobs:
  create-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Open Issue
        run: |
          gh issue create \
            --title "$TITLE" \
            --body "$BODY" \
            --label "automated-report"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TITLE: ${{ github.event.client_payload.title }}
          BODY: ${{ github.event.client_payload.body }}
